# Используем официальный образ PostgreSQL
FROM postgres:latest

# Устанавливаем переменные окружения для создания пользователя и базы данных
ENV POSTGRES_USER=test
ENV POSTGRES_PASSWORD=test_password
ENV POSTGRES_DB=test
