services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    container_name: nginx-container

  postgres:
    build:
      context: ./postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test
    container_name: postgres-container
